### ISSUE TITLE
upgrade to tesseract@5.x.x

### ISSUE THREAD

**Issue by sassman** [ccouzens/tesseract-sys#14]
are there any plans to upgrade to version tesseract@5.x.x ?

**Comment by ccouzens** [comment]
Hi,

Yes there will be. I hope to have some time this weekend to look into what's required

**Comment by sassman** [comment]
Just let me know if I can support you somehow.

**Comment by ccouzens** [comment]
I can see the build errors

```
podman container run --rm -it docker.io/ubuntu

apt-get update
apt-get install software-properties-common
add-apt-repository ppa:alex-p/tesseract-ocr-devel
apt-get update
apt-get install libtesseract5 libtesseract-dev git clang cargo pkg-config
git clone https://github.com/ccouzens/tesseract-sys.git
cd tesseract-sys
cargo test
```

As with https://github.com/ccouzens/tesseract-sys/issues/13

I get the error

```
error[E0425]: cannot find value `kMinCredibleResolution` in this scope
  --> src/lib.rs:42:9
   |
42 |         kMinCredibleResolution;
   |         ^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find value `kMaxCredibleResolution` in this scope
  --> src/lib.rs:43:9
   |
43 |         kMaxCredibleResolution;
   |         ^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error: aborting due to 2 previous errors
```

Looking at `target/debug/build/tesseract-sys-b07b2b4d0445324a/out/capi_bindings.rs` I see that the functions and structs have generated (though it is possible important ones are missing).

But `target/debug/build/tesseract-sys-b07b2b4d0445324a/out/public_types_bindings.rs` is blank (except for an autogen comment). This matches up with the error.

My `/usr/include/tesseract/publictypes.h:constexpr int kMinCredibleResolution = 70;` includes the constant.

We can compare an older version of `publictypes.h` https://github.com/tesseract-ocr/tesseract/blob/90db9b5224a3c0ceb5c84fbcae835cab3ac817d8/include/tesseract/publictypes.h

To the new version https://github.com/tesseract-ocr/tesseract/blob/main/include/tesseract/publictypes.h

We can see that the constants like `kMinCredibleResolution` were defined top level, but now they're defined in a namespace https://github.com/tesseract-ocr/tesseract/blob/main/include/tesseract/publictypes.h#L20

I suspect getting the `build.rs` script to see inside this `namespace` will allow `tesseract-sys` to support tesseract-5.0

**Comment by ccouzens** [comment]
> Just let me know if I can support you somehow.

If you like, you can check this PR :)
https://github.com/ccouzens/tesseract-sys/pull/15

**Comment by sassman** [comment]
Thanks for the PR and the feedback. 

Unfortunately I still encounter some errors. It seems that `tesseract/5.0.0/include/tesseract/publictypes.h` for example contains > c++17 syntax like `constexpr`.

I'm not sure how to tackle the thing tbh. Maybe you can give me a hint?

```sh
cargo build
   Compiling tesseract-sys v0.5.11 (/Users/d34dl0ck/workspaces/rust/tesseract-sys)
error: failed to run custom build command for `tesseract-sys v0.5.11 (/Users/d34dl0ck/workspaces/rust/tesseract-sys)`

Caused by:
  process didn't exit successfully: `/Users/d34dl0ck/workspaces/rust/tesseract-sys/target/debug/build/tesseract-sys-fafd5121b40b52eb/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=TESSERACT_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=TESSERACT_STATIC
  cargo:rerun-if-env-changed=TESSERACT_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=TESSERACT_STATIC
  cargo:rerun-if-env-changed=TESSERACT_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rustc-link-search=native=/opt/homebrew/Cellar/tesseract/5.0.0/lib
  cargo:rustc-link-lib=tesseract
  cargo:rustc-link-lib=curl
  cargo:rerun-if-env-changed=PKG_CONFIG_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=TESSERACT_STATIC
  cargo:rerun-if-env-changed=TESSERACT_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_aarch64-apple-darwin
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_aarch64_apple_darwin
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
  cargo:rustc-link-search=native="/opt/homebrew/Cellar/tesseract/5.0.0/lib"
  cargo:rustc-link-lib=tesseract

  --- stderr
  /opt/homebrew/Cellar/tesseract/5.0.0/include/tesseract/publictypes.h:33:1: error: unknown type name 'constexpr'
  /opt/homebrew/Cellar/tesseract/5.0.0/include/tesseract/publictypes.h:38:1: error: unknown type name 'constexpr'
  /opt/homebrew/Cellar/tesseract/5.0.0/include/tesseract/publictypes.h:40:1: error: unknown type name 'constexpr'
  /opt/homebrew/Cellar/tesseract/5.0.0/include/tesseract/publictypes.h:45:1: error: unknown type name 'constexpr'
  /opt/homebrew/Cellar/tesseract/5.0.0/include/tesseract/publictypes.h:33:1: error: unknown type name 'constexpr', err: true
  /opt/homebrew/Cellar/tesseract/5.0.0/include/tesseract/publictypes.h:38:1: error: unknown type name 'constexpr', err: true
  /opt/homebrew/Cellar/tesseract/5.0.0/include/tesseract/publictypes.h:40:1: error: unknown type name 'constexpr', err: true
  /opt/homebrew/Cellar/tesseract/5.0.0/include/tesseract/publictypes.h:45:1: error: unknown type name 'constexpr', err: true
  thread 'main' panicked at 'Unable to generate public types bindings: ()', build.rs:125:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by ccouzens** [comment]
Hi @sassman,

It looks like this issue

https://github.com/ccouzens/tesseract-sys/issues/4

The solution is to use `clang` installed through `brew` (package `llvm`). More detail is in the 2nd and 3rd comments
https://github.com/ccouzens/tesseract-sys/issues/4#issuecomment-748373340
https://github.com/ccouzens/tesseract-sys/issues/4#issuecomment-748489179

I believe there is an issue with the version of `clang` shipped by recent MacOS that causes a `constexpr` incompatibility with `bindgen`.
https://github.com/rust-lang/rust-bindgen/issues/1948

Hopefully that helps you get this to compile :)

---

I had been hoping that this issue would fix itself, either through Apple updating `clang` again or `bindgen` changing.

But it has been over a year now so maybe this issue needs addressing.

Possibly updates to the Readme to `tesseract-sys`. 

Or we need to find a different way of reading these 4 values out of `publictypes.h` https://github.com/tesseract-ocr/tesseract/blob/main/include/tesseract/publictypes.h#L30-L43

**Comment by sassman** [comment]
thanks for the hints!

The issue was not `clang` in my case, both llvm and apples clang versions are the same (v13.0.0)
However, my `bindgen` version was too old. A fresh install (v0.59.2) did fix that problem.

now it's only an include path issue, that I probably can fix.

```raw
  --- stderr
  /opt/homebrew/Cellar/tesseract/5.0.0/include/tesseract/capi.h:32:10: fatal error: 'stdio.h' file not found
  /opt/homebrew/Cellar/tesseract/5.0.0/include/tesseract/capi.h:32:10: fatal error: 'stdio.h' file not found, err: true
  thread 'main' panicked at 'Unable to generate capi bindings: ()', build.rs:110:10
```

**Comment by ccouzens** [comment]
You're welcome

> The issue was not clang in my case, both brews llvm and apples clang versions are the same (v13.0.0)
However, my bindgen version was too old. A fresh install (v0.59.2) did fix that problem.

That's interesting. Could I get you to do me a favour and retest this issue? https://github.com/rust-lang/rust-bindgen/issues/1948 I no longer have access to a Mac computer.

> now it's only an include path issue, that I probably can fix.

Good luck :)
