### ISSUE TITLE
Add feature `bundled` to provide self-contained binary

### ISSUE THREAD

**Issue by Toromyx** [ccouzens/tesseract-sys#21]
## Problem

I want to build a cross-platform application with integrated optical character recognition. It is not feasible to ask users to install tesseract themselves.

## Proposed Solution

Implement a feature `bundled` as in rusqlite/rusqlite#176/rusqlite/rusqlite#197 to bundle the tesseract binary together with the application. Is this a reasonable suggestion?

**Comment by Toromyx** [comment]
Yes, I would like to try implementing this feature. Should another issue be created in [leptonica-sys](https://github.com/ccouzens/leptonica-sys) or can this issue be transferred?

**Comment by ccouzens** [comment]
> Yes, I would like to try implementing this feature.

Great! Feel free to ask here for assistance if you need it.

> Should another issue be created in [leptonica-sys](https://github.com/ccouzens/leptonica-sys) or can this issue be transferred?

There's no need for a 2nd issue. We can reference this issue in any work done against `leptonica-sys`.

**Comment by Toromyx** [comment]
After [reading up on the subject](https://doc.rust-lang.org/reference/linkage.html) I came to the conclusion that I misunderstood the need for such a feature. It would be needed only for the developer experience.
For the user, the tesseract binary and dependencies are statically linked into the finished binary anyway. For some reason I assumed dynamic linking was required.

I still tried to implement the feature in [leptonica-sys](https://github.com/ccouzens/leptonica-sys) and have some talking points:
A simple compilation via [rust-lang/cc-rs](https://github.com/rust-lang/cc-rs) is not possible because the source has dependencies as seen in e.g. [.travis.yml](https://github.com/DanBloomberg/leptonica/blob/1.83.1/.travis.yml)
- [libpng](http://www.libpng.org/pub/png/libpng.html)
- [libjpeg](https://ijg.org/)
- [libtiff](https://libtiff.gitlab.io/libtiff/)
- [libopenjpeg](https://www.openjpeg.org/)
- [giflib](https://giflib.sourceforge.net/)
- [libwebp](https://github.com/webmproject/libwebp)
- ...?
  
I'm not sure whether one should
1. download the source for all these dependencies to allow a complete compilation from source.
2. create rust crates (if not already existing) for each of these dependencies and depend on them for building.
3. download already built leptonica.

The last option would practically be the same as the current workflow (apt/vcpg) except that it will happen automatically. This seems like a workaround only, and very complicated on Windows.

Option two might be feasible and be the correct separation of concerns but I'm not sure how to integrate the build process of a dependency.

So option one might be worthiest to pursue? Are there other options?

**Comment by ccouzens** [comment]
Hey,

Thank you for looking into it.

I've got a question to help me if someone creates a similar issue in the future.

>  For the user, the tesseract binary and dependencies are statically linked into the finished binary anyway. For some reason I assumed dynamic linking was required.

Do you know if this is true for all platforms (Linux, Windows, Mac) or just your current platform? Which platform are you on?

As to your question, I'm not sure what the best way to proceed would be.

> The last option would practically be the same as the current workflow (apt/vcpg) except that it will happen automatically. 

One advantage would be we'd distribute a known version, rather than the version the package manager happens to bundle.

**Comment by Toromyx** [comment]
> Do you know if this is true for all platforms (Linux, Windows, Mac) or just your current platform? Which platform are you on?

I am on Windows. I am pretty sure it is true for all platforms but it depends on the crate type: [https://doc.rust-lang.org/reference/linkage.html](https://doc.rust-lang.org/reference/linkage.html).
