### ISSUE TITLE
future cannot be sent between threads safely

### ISSUE THREAD

**Issue by DartMen** [ccouzens/tesseract-sys#5]
Im trying to wrap LepTess in a struct and construct it in an impl.

But when I try to call this wrapper from a function with the following signature:
```
pub async fn run<A, B, F>(handler: F) -> Result<(), Error>
where
    F: Handler<A, B> + Send + Sync + 'static,
    Handler<Self = F, A, B>::Fut: Future<Output = Result<B, Handler<Self = F, A, B>::Error>> + Send + 'static,
    Handler<Self = F, A, B>::Error: fmt::Display + Send + Sync + 'static,
    A: {error} + Send + Sync + 'static,
    B: Serialize + Send + Sync + 'static,
```

The compiler refuses to build with the following message:

future cannot be sent between threads safely
within `impl Future`, the trait `Send` is not implemented for `*mut tesseract_sys::TessBaseAPI`

I believe constructing/initializing leptess upfront is more efficient then to constantly 'new' it inside a fn like shown in all the examples of leptess.

I saw there is a plan to do some refac of the leptess crate, maybe this request could be taken into consideration.
https://github.com/houqp/leptess/issues/34

**Comment by ccouzens** [comment]
Hi,

I think we can make tesseract `Send`.

The change won't be done in this crate though. I've made a new version of tesseract-plumbing (commit linked to this issue) which will make its way through to leptess.

**Comment by houqp** [comment]
yep, I think it should be safe to mark them as Send

**Comment by ccouzens** [comment]
It should be working in lepess 0.12.0

**Comment by DartMen** [comment]
Nice job! 

I will test this weeknd
