### ISSUE TITLE
Compiling on macOS fails

### ISSUE THREAD

**Issue by sportfloh** [ccouzens/tesseract-sys#6]
hey,

If I try to compile tesseract-sys I get this error:

```
   Compiling tesseract-sys v0.5.5 (/private/tmp/tesseract-sys)
error: failed to run custom build command for `tesseract-sys v0.5.5 (/private/tmp/tesseract-sys)`

Caused by:
  process didn't exit successfully: `/private/tmp/tesseract-sys/target/debug/build/tesseract-sys-c7abc7d9ae9dd385/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-link-lib=tesseract

  --- stderr
  /usr/local/include/tesseract/publictypes.h:33:1: error: unknown type name 'constexpr'
  /usr/local/include/tesseract/publictypes.h:38:1: error: unknown type name 'constexpr'
  /usr/local/include/tesseract/publictypes.h:40:1: error: unknown type name 'constexpr'
  /usr/local/include/tesseract/publictypes.h:45:1: error: unknown type name 'constexpr'
  /usr/local/include/tesseract/publictypes.h:33:1: error: unknown type name 'constexpr', err: true
  /usr/local/include/tesseract/publictypes.h:38:1: error: unknown type name 'constexpr', err: true
  /usr/local/include/tesseract/publictypes.h:40:1: error: unknown type name 'constexpr', err: true
  /usr/local/include/tesseract/publictypes.h:45:1: error: unknown type name 'constexpr', err: true
  thread 'main' panicked at 'Unable to generate public types bindings: ()', build.rs:68:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

My understanding is that that bindgen is trying to compile the "wrapper_capi.h" as a C file, but "constexpr" is C++.
I installed tesseract via "brew install tesseract".

 tesseract-sys v0.5.5
tesseract v4.1.1
clang v12.0.5
rustc v1.54.0-nightly
macOS v11.4
Let me know if you need any further information.
Thanks!

**Comment by ccouzens** [comment]
Hi @sportfloh,

I think you're hitting this issue

https://github.com/ccouzens/tesseract-sys/issues/4

which has been reported to rust-bindgen here:
https://github.com/rust-lang/rust-bindgen/issues/1948

If I remember correctly the issue comes from the current Mac version of clang being weird.

The solution (if you're happy to use `brew`) is to install brew's clang

```bash
brew install llvm tesseract leptonica
```

And then you need to set a couple environment variables before running your build:

```bash
PATH="/usr/local/opt/llvm/bin:$PATH" BINDGEN_EXTRA_CLANG_ARGS='-I"/usr/local/Cellar/tesseract/4.1.1/include" -I"/usr/local/Cellar/leptonica/1.80.0/include"' cargo test
```

Hope that helps,

Chris

**Comment by sportfloh** [comment]
@ccouzens thanks! That works.
Sorry for not searching the closed issues.
Cheers!

**Comment by ccouzens** [comment]
No worries- it's nice to see people find my project useful enough to reach out 🙂
